### ISSUE TITLE
The in-tree extensions were removed and should be here

### ISSUE THREAD

**Issue by AssafKatz3** [lensapp/lens-extensions#20]
Hi,
Per [OpenLens 6.3.0 - No Logs or Shell buttons](https://github.com/lensapp/lens/issues/6823), these in-tree extensions were moved to out-of tree and should be mentioned here.
Thanks

**Comment by marafa-sugarcrm** [comment]
yes - this is missing `@alebcay/openlens-node-pod-menu`
